Adding link to a customer profile in comments lists
PrestaShop/productcomments pull request #123
Opened 2021-12-22 20:10 UTC by vallka

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Adding a link to the customer profile in BO - product comments lists (just like it was done recently in Orders list). This allows moderators to quickly navigate to comment author's profile - e.g. we use this feature to add royalty points to comments authors 
| Type?         | improvement

2021-12-23 08:18 UTC, PierreRambaud requested changes
I'm not sure it's the right way to add  links in the BO.
You've access to the SQL query in order to retrieve the customer_id, then you should be able to properly display a link, instead of using a regex in order to build a html link

2021-12-23 17:45 UTC, vallka commented
Absolutely agree that this is an awkward way of creating a link... The problem is, I cannot find a way to display ANY link in a table generated by Helper::generateList() (apart from the standard View/Edit/Delete icons). Maybe you'll give me a hint? I'll gladly re-write my solution if I'm able to do this without re-writing the Helper class.....

2021-12-24 09:57 UTC, PierreRambaud commented
> Absolutely agree that this is an awkward way of creating a link... The problem is, I cannot find a way to display ANY link in a table generated by Helper::generateList() (apart from the standard View/Edit/Delete icons). Maybe you'll give me a hint? I'll gladly re-write my solution if I'm able to do this without re-writing the Helper class.....

You're able to change the template: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/helper/HelperList.php#L196
Maybe you can find something here: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/helper/Helper.php#L74

2021-12-24 11:24 UTC, kpodemski commented
Hello @vallka 

Please take a look at this PR:
https://github.com/PrestaShop/productcomments/pull/124

Let me know if that is a solution you wanted to have :-)

2021-12-24 12:25 UTC, PierreRambaud commented
> Hello @vallka
> 
> Please take a look at this PR: #124
> 
> Let me know if that is a solution you wanted to have :-)
> 
> You can see how it is done, basically, every field rendered by the `HelperList` may be decorated through the `callback`, and this was the easiest way create a link.

I like what you did and I approve :p

2021-12-24 15:44 UTC, vallka commented
Exactly what I wanted to do :)

On Fri, 24 Dec 2021 at 11:24, Krystian Podemski ***@***.***>
wrote:

> Hello @vallka <https://github.com/vallka>
>
> Please take a look at this PR:
> #124 <https://github.com/PrestaShop/productcomments/pull/124>
>
> Let me know if that is a solution you wanted to have :-)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PrestaShop/productcomments/pull/123#issuecomment-1000800813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADBMNHO4Y2YGPIWUU4NLZYTUSRJ53ANCNFSM5KTJSGBQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-27 08:34 UTC, PierreRambaud commented
Closed in favor of #124
Thank you @vallka and @kpodemski

2021-12-27 08:34 UTC, closed without merging