Fix hookFilterProductContent to allow hook chain
PrestaShop/productcomments pull request #137
Opened 2022-03-14 21:17 UTC by idnovate

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | All hookFilter* functions should always return the following: return $params; Returning $params ensures that other modules in the same hook chain receive the correct $params argument.
| Type?         | bug fix / critical
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | 
| How to test?  | To reproduce the bug install an additional module with hookFilterProductContent AFTER the productcomments and run in debug mode.

2022-03-15 07:08 UTC, PierreRambaud submitted a review, later dismissed
You break phpstan and php cs fixer with your fix

2022-03-17 10:24 UTC, kpodemski commented
@idnovate, you have to change docblock in the hook implementation to not return void but array :)

2022-03-17 10:39 UTC, idnovate commented
> @idnovate, you have to change docblock in the hook implementation to not return void but array :)

Done. Is it not easier for you to apply and commit this patch than wait for the author? Or even when there's just a change in a single line but placed tabs instead of spaces. Which is the aim of it?

2022-03-17 10:53 UTC, kpodemski commented on productcomments.php
> +
```suggestion

```

2022-03-17 10:55 UTC, kpodemski commented on productcomments.php
>          ];
```suggestion
        ];

```

2022-03-17 10:56 UTC, kpodemski commented
@idnovate it depends, sometimes we can use GH UI to request changes in a specific part of the file, but this part with the comment wasn't available :D

2022-03-17 10:56 UTC, kpodemski approved these changes

2022-03-17 10:57 UTC, kpodemski commented
Thanks @idnovate 

I'm sending this PR to our QA :)

2022-03-18 17:17 UTC, khouloudbelguith requested changes
Hi @idnovate,

I checked with the module https://github.com/PrestaShop/ps_qualityassurance/
![image](https://user-images.githubusercontent.com/16067358/159051104-e2b95120-f3b1-45f4-ab6b-2e3f8a81d59a.png)

**Without PR**, I have this exception on the FO > Product page 
![image](https://user-images.githubusercontent.com/16067358/159050902-12b618dd-1028-4aed-9543-0c9882260b2c.png)

**With PR**
1. First case
![image](https://user-images.githubusercontent.com/16067358/159051212-bd8c58e1-9659-42ba-b437-b72f23bdd95d.png)

=> OK 
![image](https://user-images.githubusercontent.com/16067358/159051284-b4d46b22-810e-460a-a4e7-177fc94cc86f.png)

2. Second case 
![image](https://user-images.githubusercontent.com/16067358/159051368-45e11e7f-5128-40c4-9bf1-8ddcaec5bd15.png)

=> NOK 
![image](https://user-images.githubusercontent.com/16067358/159051405-5bf4bb97-1ead-4348-8557-8c09ca63f69d.png)

Thanks to check and feedback!

2022-03-18 17:22 UTC, kpodemski commented
@khouloudbelguith hi, how do you test second scenario? do you have return $params?

2022-06-17 12:03 UTC, khouloudbelguith reviewed
Hi @kpodemski,

I tried the first case with `dump ($params);` => NOK
I attached a screen record

https://user-images.githubusercontent.com/16067358/174294189-2126fad4-50d8-4246-8964-43c841d7c8f3.mp4

I tried the second solution `return $params; ` => NOK
![image](https://user-images.githubusercontent.com/16067358/174294386-d5cc6cf5-2604-4518-a9a4-6ec1e2b03bd3.png)

I attached a screen record

https://user-images.githubusercontent.com/16067358/174294488-144e4d58-d888-45e6-88da-25363390a901.mp4

Thanks!

2022-06-25 20:26 UTC, kpodemski commented
Hello @khouloudbelguith 

The fix is valid. Please test it with the example module. Maybe there are some specific things related to the `ps_qualityassurance` module. Example module:
[filterproductcontent.zip](https://github.com/PrestaShop/productcomments/files/8985501/filterproductcontent.zip)

Information:

1. After the installation, this module will add a `(filtered)` text to the product name
2. Before the fix of `productcomments`, this module won't work if the `productcomments` will be first in the `Design -> Positions -> filterProductContent` hook
3. It will work after the fix because the return of the `productcomments` module will be an array.

This issue is critical as it affects some very popular hosting environments that use LiteSpeed cache. (the litespeedmodule is affected by this bug)

2022-07-01 11:58 UTC, jolelievre approved these changes
Thanks @idnovate 

It's a good fix for the module itself, but maybe we should make chained hook execution more resilient to invalid implementation in the core (like checking that the hook actually returned something before replacing the chained arguments)

2022-08-11 08:02 UTC, kpodemski commented
hey @khouloudbelguith 

Any chance to put it on your schedule? it's quite a critical issue :(

2022-08-11 16:54 UTC, khouloudbelguith approved these changes
Hi @idnovate, @kpodemski,

Thanks for the details and sorry for the delay.
It is ok :heavy_check_mark: 
I check this PR with 1.7.8.x, 8.0.x and develop.
I installed those modules:

- [filterproductcontent.zip](https://github.com/PrestaShop/productcomments/files/9310454/filterproductcontent.zip)
- [productcomments_filter_test.zip](https://github.com/PrestaShop/productcomments/files/9310455/productcomments_filter_test.zip)
- https://github.com/PrestaShop/ps_qualityassurance/

https://user-images.githubusercontent.com/16067358/184190207-8d2f5801-d2a6-4bfa-b5f6-48b460c14056.mp4


https://user-images.githubusercontent.com/16067358/184190216-ea8942e7-17b4-4981-a2db-dce5359e5c10.mp4


https://user-images.githubusercontent.com/16067358/184190249-bce50df2-a144-40fa-9f52-36f7625fbf7c.mp4

I launched the automatic tests on the FO/product_page => OK
I launched the automatic tests on the BO/Module manager => OK

Thanks!

2022-08-11 19:08 UTC, jolelievre commented
Thanks @idnovate and @khouloudbelguith

2022-08-11 19:08 UTC, merged