Improved lastname anonymization
PrestaShop/productcomments pull request #149
Opened 2022-11-18 12:31 UTC by kpodemski

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Anonymization now works for guests and customers
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#30345.
| How to test?  | Please indicate how to best verify that this PR is correct.

2022-11-18 13:17 UTC, leemyongpakvn commented on controllers/front/ListComments.php
> +                $productComment['lastname'] = count($parts) > 1 ? array_pop($parts) : '';
I think `$productComment['firstname'] = $parts[0];` will be better.
Because this variable is used only one time and its name looks confused.

2022-11-18 16:46 UTC, matks reviewed
Code seems ok but I think we need to help developers to understand this new logic. Maybe add a comment or create a private method with a very explicit name?

Also PHPStan is not happy
```
 -- ------------------------------------------------------------------ 
     Error                                                             
 -- ------------------------------------------------------------------ 
     Ignored error pattern #Access to an undefined property            
     Cookie::\$id_customer.# was not matched in reported errors.       
     Ignored error pattern #Access to an undefined property            
     Cookie::\$id_guest.# was not matched in reported errors.          
     Ignored error pattern #Access to an undefined property            
     HelperList::\$list_id.# was not matched in reported errors.       
     Ignored error pattern #Access to an undefined property            
     HelperList::\$shopLinkType.# was not matched in reported errors.  
 -- ------------------------------------------------------------------ 
 ```

2022-11-19 03:36 UTC, leemyongpakvn reviewed
as old code has 1 `isset` check at line 67

2022-12-09 10:19 UTC, kpodemski commented on controllers/front/ListComments.php
>              if (empty($productComment['customer_name']) && !isset($productComment['firstname']) && !isset($productComment['lastname'])) {
thanks @leemyongpakvn, you're right :))

2022-12-09 10:59 UTC, Hlavtox approved these changes

2022-12-09 11:11 UTC, micka-fdz requested changes

2022-12-09 11:11 UTC, micka-fdz commented on controllers/front/ListComments.php
> +            $product['customer_name'] = htmlentities($productComment['customer_name']);
I think you used wrong variable here.
```suggestion
            $productComment['customer_name'] = htmlentities($productComment['customer_name']);
```

2022-12-09 11:21 UTC, kpodemski commented on controllers/front/ListComments.php
> +            $product['customer_name'] = htmlentities($productComment['customer_name']);
@micka-fdz nice catch!

2022-12-09 13:04 UTC, HanaRebaiQA commented
Hello @kpodemski 

Thanks for your PR. Can we have a second review before starting testing following @micka-fdz 'feedback review ?

2022-12-09 13:06 UTC, micka-fdz approved these changes

2022-12-09 13:23 UTC, Hlavtox approved these changes

2022-12-09 14:34 UTC, MhiriFaten approved these changes
Hello @kpodemski ,

I have checked your PR, the issue is well fixed!

[Untitled_ Dec 9, 2022 3_33 PM.webm](https://user-images.githubusercontent.com/111756615/206725376-3df4fbaf-3aee-4d63-b5fa-4f1973ee26e5.webm)

So it's QA approved :heavy_check_mark: 

Many thanks !

2022-12-09 14:37 UTC, merged

2022-12-09 14:37 UTC, Hlavtox commented
Thank you @kpodemski!!!!