If user mistakenly attempts to delete a comment, fail gracefully
PrestaShop/productcomments pull request #190
Opened 2023-11-16 14:50 UTC by matks

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixes 2 issues described in https://github.com/PrestaShop/PrestaShop/issues/34512 : missing redirect after successfull deletion of a comment, and missing handling of bad input when delete is called on a comment that does not exist
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/34512
| How to test?  | Please follow the ticket instructions

2023-11-16 15:52 UTC, nicosomb requested changes

2023-11-16 15:52 UTC, nicosomb commented on productcomments.php
> +            if ($comment ===  null) {
```suggestion
            if ($comment === null) {
```

2023-11-16 16:38 UTC, nicosomb approved these changes

2023-11-17 01:11 UTC, leemyongpakvn approved these changes
Tested OK. Indeed, _The comment cannot be found to delete_ :ok_hand:

2023-11-17 13:34 UTC, florine2623 approved these changes
Hello @matks ,

Tested on 1.7.8.x, 8.0.x, 8.1.x and develop.

Works as expected, no more exception.

https://github.com/PrestaShop/productcomments/assets/16019289/c231ed5f-5907-4190-8f52-449c06fa18bf

It is QA ✅

2023-11-17 13:49 UTC, merged

2023-11-17 13:49 UTC, leemyongpakvn commented
Thanks @matks and @florine2623