Set 5 stars default
PrestaShop/productcomments pull request #196
Opened 2024-01-12 23:06 UTC by alfonsolr09

Customers do not usually modify the stars since they go unnoticed. I have a store with reviews from very happy customers and they all leave 3 stars because they don't see what comes predefined

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2024-01-12 23:07 UTC, alfonsolr09 commented
Another solution would be to not set anything by default and if the client sends the form without marking any stars, an error message appears

@Hlavtox wdyt?

2024-01-13 04:17 UTC, leemyongpakvn commented
We already have a suggestion to [Make rating mandatory](PrestaShop/PrestaShop/issues/26001) but no one implement it yet ;)
I'd prefer Configurable default rating to a Fixed value.

2024-01-15 17:19 UTC, matthieu-rolland reviewed
We definitely can't merge this without consulting the product team (@PrestaShop/product-council @MatShir )

2024-01-15 17:31 UTC, fabienvallon commented
> We definitely can't merge this without consulting the product team (@PrestaShop/product-council @MatShir )

I think make rating mandatory is the good choice.
Waiting for PR / contribution :)

2024-01-15 21:04 UTC, alfonsolr09 commented
I think no. For the merchant, it is better that the 5-star option comes predefined.

The customer who wants to leave a negative review will be careful to select 1 star.

2024-01-16 09:13 UTC, RosaBenouamer commented
I agree with @fabienvallon. 
I share your opinion @alfonsolr09 that's a problem that the merchant is penalized.
But as the problem is "Customers do not usually modify the stars since they go unnoticed." 
This PR doesn't completely resolve the issue. Indeed still have 5 is not a good thing too.
It could be better making the rating mandatory like this the client will really be aware of his rate.

2024-01-16 17:15 UTC, matthieu-rolland commented
> I agree with @fabienvallon. I share your opinion @alfonsolr09 that's a problem that the merchant is penalized. But as the problem is "Customers do not usually modify the stars since they go unnoticed." This PR doesn't completely resolve the issue. Indeed still have 5 is not a good thing too. It could be better making the rating mandatory like this the client will really be aware of his rate.

should this be specified somewhere or can this modification be made in this PR and merged directly after qa tests ?

2024-01-16 18:32 UTC, alfonsolr09 commented
This pr could be merged for now as a provisional improvement. Since we do not have a forecast date for someone to make the other improvement.

2024-01-17 05:02 UTC, RosaBenouamer commented
@fabienvallon if it's ok for you it's ok for me too. It make sens :-)

2024-01-19 15:08 UTC, matthieu-rolland commented
> This pr could be merged for now as a provisional improvement. Since we do not have a forecast date for someone to make the other improvement.

I'm not even sure this is legal (to have customer push a 5 stars review without him having chosen a specific score) 🤔 

@fabienvallon and @RosaBenouamer (product team) have decided that instead the rating should be mandatory, do you think it's a modification you could make in this pull request ?

2024-01-19 15:09 UTC, matthieu-rolland requested changes
> This pr could be merged for now as a provisional improvement. Since we do not have a forecast date for someone to make the other improvement.

I'm not even sure this is legal (to have customer push a 5 stars review without him having chosen a specific score) 🤔 

@fabienvallon and @RosaBenouamer (product team) have decided that instead the rating should be mandatory, @alfonsolr09 do you think it's a modification you could make in this pull request ?

2024-01-19 15:31 UTC, alfonsolr09 commented
I don't think I'm qualified to do that job. In relation to legality issues, before you marked 3 stars by default, what is the problem that now the default is 5?

2024-01-19 15:31 UTC, alfonsolr09 commented
I don't think I'm qualified to do that job. In relation to legality issues, before you marked 3 stars by default, what is the problem that now the default is 5?

2024-01-22 17:11 UTC, matthieu-rolland reviewed
> I don't think I'm qualified to do that job. In relation to legality issues, before you marked 3 stars by default, what is the problem that now the default is 5?

well 3 is average, 5 is maximum...  but in both cases it's weird.

There's now a pull request to make the rating mandatory 👍 
https://github.com/PrestaShop/productcomments/pull/197

2025-10-31 10:20 UTC, ga-devfront commented
Having not heard from the author for over a year and a solution having been proposed, I am taking the liberty of closing this pull request.

2025-10-31 10:20 UTC, closed without merging