Prevent MakeRatingMandatory feature breaks review in 3rd party theme
PrestaShop/productcomments pull request #210
Opened 2024-05-28 14:11 UTC by leemyongpakva

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Third party themes with override template for productcomments 7.0.0 will face bug when submitting review if the translation string for MakeRatingMandatory is not added in themes yet. <br/> The issue was locally solved in hummingbird beta but still happens in hummingbird 0.2.0.<br/> This PR solve the issue globally for all themes. If the shop owner want to use their own translation string then they must take care escape characters themselves ;)
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#36093
| How to test?  | Test with productcomments 7.0.0 and hummingbird 0.2.0 on PS 1.7.8+. <br/> Before PR you will see the issue as described in the above ticket, after PR the issue won't happen.

2024-06-26 10:36 UTC, kpodemski commented on views/js/post-comment.js
> +    productCommentMandatoryMessage = 'Please choose a rating for your review.';
It has to be a translatable phrase.

2024-06-26 10:36 UTC, kpodemski requested changes
The text you added has to be a translatable phrase.

2024-06-26 15:33 UTC, pawelkierklo commented
Please put this code to hook after line 7 on **product-comments-list.tpl**

> var productCommentMandatoryMessage = '{l|escape:'javascript' s='Please choose a rating for your review.' d='Modules.Productcomments.Shop'}';
> </script>

and please **don't change file post-comment.js**

2024-06-28 06:14 UTC, leemyongpakva commented on views/js/post-comment.js
> +    productCommentMandatoryMessage = 'Please choose a rating for your review.';
Certainly it is, [in this template file](https://github.com/PrestaShop/productcomments/blob/dev/views/templates/hook/post-comment-modal.tpl#L28). This PR is a patch for hummingbird 0.2.0 or third-party themes that has their own override post-comment-modal.tpl - **not** implemented productcomment 7.0.0's new review-mandatory  feature **yet**. In these cases, a non-technical shop-owner will just complain _''my client can not do review after upgrading productcomment to v7.0.0''_ , then an English phrase is clearly better than a broken review.

2024-06-28 06:23 UTC, leemyongpakva commented
@pawelkierklo hummingbird theme has its own override [product-comments-list.tpl](https://github.com/PrestaShop/hummingbird/blob/develop/modules/productcomments/views/templates/hook/product-comments-list.tpl), so putting productCommentMandatoryMessage declaration in [module template file](https://github.com/PrestaShop/productcomments/blob/dev/views/templates/hook/product-comments-list.tpl) won't solve the problem.

2025-10-31 14:15 UTC, ga-devfront commented
In the `views/templates/hook/post-comment-modal.tp` template, the variable is already defined. If a third-party theme overrides it and doesn't use the modal, we don't want to use an untranslated string. Therefore, I'm closing the pull request.

2025-10-31 14:15 UTC, closed without merging