Fix posted modal backdrop
PrestaShop/productcomments pull request #95
Opened 2021-01-06 17:46 UTC by LukasK13

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When submitting a new review, the  confirmation dialog appears to be behind the backdrop. This is likely caused by a timing issue, which is the reason why I added a delay.
| Type?         | bug fix
| BC breaks?    | yes / no
| Deprecations? | no
| Fixed ticket? | None
| How to test?  | Create a new review and check if the confirmation dialog is in foreground

2021-05-14 21:10 UTC, matks requested changes
Hi, thanks for this contribution!

Your pull request does not seem to fix any issue, consider [creating one](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (see note below) and linking it by writing `Fixes #1234`. Then a QA member will explore your GitHub issue.

This will help us understand the situation. A delay does not always happen, maybe there is some conditions to be met. Adding a timeout is not the first solution we should look for.

2021-05-14 21:11 UTC, matks commented
Information about linked issues

Opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

2021-05-16 18:37 UTC, LukasK13 commented
fixes #24516

2021-11-15 09:00 UTC, PierreRambaud commented
The issue has been closed, i'm closing it, but feel free to reopen the issue if you think the problem is still relevant

2021-11-15 09:00 UTC, closed without merging